# ------------------------------------------------------------------------------
# Pull base image
FROM fullaxx/ubuntu-desktop
MAINTAINER Brett Kuskie <fullaxx@gmail.com>

# ------------------------------------------------------------------------------
# Set environment variables
ENV DEBIAN_FRONTEND noninteractive
ENV LANG C
ENV TZ Etc/Zulu
ENV CHROMEURL "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
ENV CHROMEDEB "/tmp/chrome.deb"

# ------------------------------------------------------------------------------
# Update apt
RUN apt-get update

# ------------------------------------------------------------------------------
# Install basic tools
RUN apt-get install -y apcalc apt-transport-https bash-completion build-essential \
bridge-utils ca-certificates caja cdw cgdb cmake colordiff colortail curl \
dos2unix diffstat evince file galculator gdb gedit gimp git gkrellm gnupg2 htop \
hexcompare hexcurse hexdiff hexedit hexer iftop iperf kmod less lsof \
man mc most nano nedit netcat nload nmon patch parallel psmisc \
rsync simpleburn software-properties-common sudo tree tzdata wget unzip xfe xterm

# ------------------------------------------------------------------------------
# Install Docker
RUN wget -q -O- https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io

# ------------------------------------------------------------------------------
# Install Chrome
RUN wget ${CHROMEURL} -O ${CHROMEDEB} && \
dpkg -i ${CHROMEDEB} || (set -e; apt-get update; apt-get install -f -y) && \
rm ${CHROMEDEB}

# ------------------------------------------------------------------------------
# Install VSCode
# RUN wget -q -O- https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
# add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" && \
# apt-get update && apt-get install -y code libasound2

# ------------------------------------------------------------------------------
# Install platform tools
RUN apt-get install -y firefox gnuradio jupyter-notebook libreoffice \
maven netbeans octave openjdk-11-jdk redis

# ------------------------------------------------------------------------------
# Install dev tools
RUN apt-get install -y bluefish chaosreader cmake ctags doxygen emacs geany \
libcurl4 libczmq4 libmicrohttpd12 libpcap0.8 libssl1.1 libxml2 libzmq5 \
medit nmap nmapfe screen sqlite3 subversion terminator tmux tcpdump \
valgrind vim vim-gtk3 wireshark zenmap

# ------------------------------------------------------------------------------
# Install dev libraries
RUN apt-get install -y gnuradio-dev libzmq-java \
libcurl4-openssl-dev libczmq-dev libhiredis-dev libmicrohttpd-dev libpcap-dev \
libsqlite3-dev libssl-dev libxml2-dev libzmq3-dev

# ------------------------------------------------------------------------------
# Install python libraries
RUN apt-get install -y cython cython3 \
python-hiredis python3-hiredis python-redis python3-redis \
python-pip python3-pip python-virtualenv python-zmq python3-zmq

# ------------------------------------------------------------------------------
# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

# ------------------------------------------------------------------------------
# Install scripts and configuration files
# COPY conf/menu.xml /usr/share/ubuntu-desktop/openbox/

# ------------------------------------------------------------------------------
# Expose ports
EXPOSE 5901

# ------------------------------------------------------------------------------
# Define default command
CMD ["/app/app.sh"]
